
-- Run this script in the Supabase SQL Editor to create the tables

-- Users Table
CREATE TABLE IF NOT EXISTS "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text UNIQUE NOT NULL,
  "displayName" text NOT NULL,
  "email" text,
  "passwordHash" text NOT NULL
);

-- Customers Table
CREATE TABLE IF NOT EXISTS "customers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "address" text,
  "vat" text,
  "email" text,
  "phone" text,
  "pec" text,
  "recipientCode" text,
  "ownerUserId" bigint REFERENCES "users" ("id")
);

-- Articles Table
CREATE TABLE IF NOT EXISTS "articles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" text NOT NULL,
  "description" text NOT NULL,
  "unitPrice" numeric NOT NULL,
  "unit" text NOT NULL,
  "vat" numeric NOT NULL,
  "ownerUserId" bigint REFERENCES "users" ("id")
);


-- Quotes Table
CREATE TABLE IF NOT EXISTS "quotes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" text NOT NULL,
  "date" timestamptz NOT NULL,
  "customerName" text NOT NULL,
  "customerAddress" text NOT NULL,
  "customerVat" text NOT NULL,
  "items" jsonb NOT NULL DEFAULT '[]',
  "attachments" jsonb DEFAULT '[]',
  "tocTextAbove" text,
  "tocText" text,
  "premessaText" text,
  "premessaHardwareImages" jsonb DEFAULT '[]',
  "premessaHardwareImageHeight" integer,
  "premessaHardwareImageCount" integer,
  "premessaHardwareImageScale" integer,
  "softwareText" text,
  "softwareImages" jsonb DEFAULT '[]',
  "softwareImageHeight" integer,
  "softwareImageCount" integer,
  "softwareImageScale" integer,
  "targetAudienceImages" jsonb DEFAULT '[]',
  "targetAudienceImageHeight" integer,
  "targetAudienceImageCount" integer,
  "targetAudienceImageScale" integer,
  "descrizioneProdottiText" text,
  "descrizioneProdottiImages" jsonb DEFAULT '[]',
  "descrizioneProdottiImageCount" integer,
  "descrizioneProdottiImageFit" text,
  "descrizioneProdottiFirstImageScale" integer,
  "conditionsList" jsonb DEFAULT '[]',
  "conditionsCount" integer,
  "subtotal" numeric NOT NULL,
  "vatTotal" numeric NOT NULL,
  "total" numeric NOT NULL,
  "notes" text,
  "createdAt" timestamptz DEFAULT now(),
  "ownerUserId" bigint REFERENCES "users" ("id"),
  "attachmentsPosition" text,
  "customerId" bigint REFERENCES "customers" ("id"),
  "leasing" jsonb,
  "showTotals" boolean DEFAULT true
);

-- Settings Table
CREATE TABLE IF NOT EXISTS "settings" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" bigint REFERENCES "users" ("id"),
  "companyName" text NOT NULL,
  "companyAddress" text NOT NULL,
  "companyVat" text NOT NULL,
  "companyEmail" text NOT NULL,
  "companyPec" text,
  "companyPhone" text NOT NULL,
  "companyRecipientCode" text,
  "bankInfo" text NOT NULL,
  "logoUrl" text,
  "logoData" text,
  "defaultHardwareImage" text,
  "defaultSoftwareImage" text,
  "defaultTargetImage" text,
  "defaultDescrizioneImage" text,
  "defaultHardwareHeight" integer,
  "defaultSoftwareHeight" integer,
  "defaultTargetHeight" integer,
  "defaultDescrizioneFirstHeight" integer,
  "contractPagesText" text,
  "nextQuoteNumber" integer NOT NULL,
  "quoteNumberPrefix" text NOT NULL,
  "defaultVat" numeric NOT NULL,
  "attachmentsDefaults" jsonb
);

-- Insert Default Admin User (password: admin) if not exists
INSERT INTO "users" ("username", "displayName", "email", "passwordHash")
VALUES ('admin', 'Admin', '', 'admin')
ON CONFLICT ("username") DO NOTHING;

-- Migration: Add premessaHardwareImageScale column (Run this if the table already exists)
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "premessaHardwareImageScale" integer DEFAULT 100;

-- Migration: Add descrizioneProdottiCaptions column
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "descrizioneProdottiCaptions" jsonb DEFAULT '[]';
